INSERT INTO 'Kunde' (Email,Telefonnummer,Vorname,Nachname,Passwort,Postleitzahl,Strasse,Hausnummer,Adresszusatz) VALUES
('jkw-123@protonmail.com','09176667570','Loreta','Amália','MUy5t4(C<7a7v7M?','12529','Hauptstraße','1',''),
('menacho18@tronques.ml','31319766758','Usama','Usama',',8Sn446)7kK7V_Zh','14532','Schulstraße','19',''),
('solymar@mymailcr.com','14166836478','Raimund','Hipolit','!:g7E!c9pn7wWk-S','14641','Gartenstraße','23','a'),
('janutial@livegolftv.com','85503079458','Karlene','Gláucio','M.#VBNCEqTd_a%)}','14641','Dorfstraße','11',''),
('yulia1803@gmailya.com','43498957627','Baltazar',' Tzion','S,Vn.nEgGenK#}7u','61118','Buchenweg','91','')