
INSERT INTO "Zahlungsart" VALUES(1,'PayPal','menacho18@tronques.ml','Usama Usama','','','','','');
INSERT INTO "Zahlungsart" VALUES(2,'Uberweisung','solymar@mymailcr.com','Raimund Hipolit','','','932839283834627','513 900 00','Volksbank Mittelhessen eG');
INSERT INTO "Zahlungsart" VALUES(3,'Kreditkarte','jkw-123@protonmail.com','Loreta Amália','5252662525','383','','','');
INSERT INTO "Zahlungsart" VALUES(4,'PayPal','janutial@livegolftv.com','Karlene Gláucio','','','','','');
INSERT INTO "Zahlungsart" VALUES(5,'PayPal','janutial@livegolftv.com','Karlene Gláucio','','','','','');